apiVersion: v1
kind: Secret
metadata:
  name: aksdemocosmos
type: Opaque
data:
  connectionstring: #{CosmosDbConnectionString}#
---
apiVersion: v1
kind: Secret
metadata:
  name: aksdemoredis
type: Opaque
data:
  connectionstring: #{RedisConnectionString}#
